name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: mkdir_build
      run: mkdir build
    - name: make
      run: cd build && cmake .. && cmake --build .
